### ISSUE TITLE
Ender Shot Error: Calling seekTarget from base, throws NoSuchMethodError

### ISSUE THREAD

**Issue by Tarlach** [TrainerGuy22/Reliquary#207]
Running a forge server and testing out the handgun with Ender Shot. Fired without a target, and the server instantly crashed safely, offloading player data. However now the server will crash repeatedly whenever I load in.

**Comment by Tarlach** [comment]
Stack Trace:

<code>java.lang.NoSuchMethodError: xreliquary.entities.shot.EntityShotBase.func_70016_h(DDD)V
 at xreliquary.entities.shot.EntityShotBase.seekTarget(EntityShotBase.java:455)
 at xreliquary.entities.shot.EntityEnderShot.doFlightEffects(EntityEnderShot.java:64)
 at xreliquary.entities.shot.EntityShotBase.func_70071_h_(EntityShotBase.java:186)
 at net.minecraft.world.World.func_72866_a(World.java:2070)
 at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
 at net.minecraft.world.World.func_72870_g(World.java:2034)
 at net.minecraft.world.World.func_72939_s(World.java:1887)
 at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
 at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
</code>

**Comment by Tarlach** [comment]
Error was associated with 1.2.223, apologies.
