### ISSUE TITLE
[1.10.2] Client crash when a player fires the hunters handgun.

### ISSUE THREAD

**Issue by ProsperCraft** [TrainerGuy22/Reliquary#233]
http://pastebin.com/psPszNzK

Description: Ticking entity
 
java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Integer
    at xreliquary.entities.shot.EntityShotBase.getColor(EntityShotBase.java:281)
    at xreliquary.entities.shot.EntityShotBase.spawnPotionParticles(EntityShotBase.java:267)
    at xreliquary.entities.shot.EntityShotBase.func_70071_h_(EntityShotBase.java:189)
    at net.minecraft.world.World.func_72866_a(World.java:1964)
    at net.minecraft.world.World.func_72870_g(World.java:1934)
    at net.minecraft.world.World.func_72939_s(World.java:1750)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by P3pp3rF1y** [comment]
Please log issues under https://github.com/P3pp3rF1y/Reliquary/issues, I wasn't aware of these until I randomly checked this fork today.

**Comment by P3pp3rF1y** [comment]
Also steps to recreate would be nice as I have seen something like this previously but was unable to recreate it myself.
