### ISSUE TITLE
(SEVERE) Client randomly crash even when not using the Hunter's Handgun [same crashlog]

### ISSUE THREAD

**Issue by ExDomino** [TrainerGuy22/Reliquary#235]
Reliquary-1.10.2-1.3.3.585.jar (Java 8)
java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Integer
	at xreliquary.entities.shot.EntityShotBase.getColor(EntityShotBase.java:281)
	at xreliquary.entities.shot.EntityShotBase.spawnPotionParticles(EntityShotBase.java:267)
	at xreliquary.entities.shot.EntityShotBase.func_70071_h_(EntityShotBase.java:189)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ExDomino** [comment]
Something really strange: a friend of mine, on the same server, same version of Java, the same Java arguments, the same amount of RAM and the same mods and version of them, (in short: the same environment, the Curse client with a new profile for our modpack using the native version of Java provided by Curse itself [Java 8u25] without arguments), he doesn't crash when it uses the same item, but I do crash when he uses it near of me. We tryed to find out why he doesn't crash and why I do crash, without success! We're both on Windows 7.

**Comment by ExDomino** [comment]
My friend that did not crash before now often randomly crash for the same exact reason without using any of your items that come with your mod. It's begening to be unplayable even if we don't use your mod.

**Comment by P3pp3rF1y** [comment]
Please log these under https://github.com/P3pp3rF1y/Reliquary/issues, wasn't aware of the issue until randomly checking today. 
It seems to me like these errors are caused by shots that were fired, but didn't "die" before the update to Reliquary with potion effect update to shots. I may need to do some investigation if there's an easy way to kill these entities. 
If you're actually able to recreate this please post the steps.
