### ISSUE TITLE
Pyromancer's staff blaze mode causes error/client disconnect if mob griefing is turned off

### ISSUE THREAD

**Issue by Aranduran** [TrainerGuy22/Reliquary#243]
I'm playing on Reliquary v1.3 (Reliquary-1.14.4-1.3.4.1009.jar) on a server, and I find that when I use the blaze mode of the pyromancer's staff, if mob griefing is not enabled, using the blaze mode of the staff causes the client to be disconnected with an internal server error. The ghast mode works fine, interestingly enough. I suspect behind the scenes it's actually firing a fire charge as  though from a dispenser.

I see that the mod is updated to minecraft 16 so I understand if you don't want/can't fix it in 14. I don't see this issue logged so I'm guessing it still exists in higher versions.

Thanks!

**Comment by Aranduran** [comment]
Actually it is still causing the issue even with mobGriefing enabled. It worked for me once when it was enabled, but I'm not sure why. Here's the exception:
Failed to handle packet for <ip removed>
net.minecraft.crash.ReportedException: Ticking player
at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:428) ~[?:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:848) [?:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) [?:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766) [?:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [?:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.func_213324_a(DFZ)Lnet/minecraft/util/math/RayTraceResult;
at xreliquary.items.PyromancerStaffItem.onUsingTick(PyromancerStaffItem.java:224) ~[?:1.14.4-1.3.4.1009]
at net.minecraftforge.common.extensions.IForgeItemStack.onUsingTick(IForgeItemStack.java:247) ~[?:?]
at net.minecraft.entity.LivingEntity.func_184608_ct(LivingEntity.java:2454) ~[?:?]
at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1966) ~[?:?]
at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232) ~[?:?]
at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:365) ~[?:?]
... 8 more
